

services:
  dhcp-server:
    image: networkboot/dhcpd
    container_name: serverdhcp
    networks:
      dhcp__network:
        ipv4_address: 172.16.0.2
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./dhcp/isc-dhcp-server:/etc/Default/isc-dchp-server
    ports:
      - "67:67/udp"  # DHCP
  ubuntu-client:
    image: ubuntu:latest
    container_name: clientedhcp
    networks:
      - dhcp__network
    command: sleep infinity    


networks:
  dhcp__network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1

